## 1.	Write a Python Program to Add Two Matrices?

In [4]:
import numpy as np

np.random.seed(0)
arr1 = np.random.randn(3,3)
arr1

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [5]:
np.random.seed(1)
arr2 = np.random.randn(3,3)
arr2

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ,  0.3190391 ]])

In [7]:
# arr1 + arr2
arr1 + arr2

array([[ 3.38839771, -0.21159921,  0.45056623],
       [ 1.16792458,  2.73296562, -3.27881658],
       [ 2.69490018, -0.91256411,  0.21582024]])

## 2.	Write a Python Program to Multiply Two Matrices?

In [8]:
arr1@arr2 # legitmate multiplication of two arrays

array([[ 4.14378767, -1.47789334, -1.54044424],
       [-0.06901259,  0.98922881, -5.79362332],
       [ 1.52557578, -0.63363746, -0.18638624]])

## 3.	Write a Python Program to Transpose a Matrix?

In [9]:
arr1.T

array([[ 1.76405235,  2.2408932 ,  0.95008842],
       [ 0.40015721,  1.86755799, -0.15135721],
       [ 0.97873798, -0.97727788, -0.10321885]])

**OR:**

In [11]:
arr1.transpose()

array([[ 1.76405235,  2.2408932 ,  0.95008842],
       [ 0.40015721,  1.86755799, -0.15135721],
       [ 0.97873798, -0.97727788, -0.10321885]])

## 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [35]:
words = "I don't feel like it's gonna do any good!"

x = words.split()
sorted(x)

['I', 'any', 'do', "don't", 'feel', 'gonna', 'good!', "it's", 'like']

## 5.	Write a Python Program to Remove Punctuation From a String?

In [77]:
s = "You mightn't believe in yourself, and I can make you count 50 things by yourself right now, \
right here, that you are undervaluing yourself. You up for it, eh?"
s

"You mightn't believe in yourself, and I can make you count 50 things by yourself right now, right here, that you are undervaluing yourself. You up for it, eh?"

In [78]:
def rem_punc(s):
    lst = ['']
    
    for i in s.split():
        if i.isalnum(): # does not contain any punctuations!
            lst.append(i)
            
        else: # does contain punctuations.
            if len(i) == 1:
                continue 
            elif i[-1].isalnum(): # to make sure words like don't, won't, etc. won't get missed out! 
                lst.append(i)
            else: # i.e. to say if you use punctuations without giving space after words.
                lst.append(i[:-1])
                
    return lst[0] + ' '.join(lst[1:]) #just to avoid the space before the first letter of the string.

rem_punc(s)

"You mightn't believe in yourself and I can make you count 50 things by yourself right now right here that you are undervaluing yourself You up for it eh"