In [1]:
import numpy as np, pandas as pd
import random

## 1.	Write a Python Program to find sum of array?

In [2]:
np.random.seed(0)
arr = np.random.randn(3,3) #generating a 3-Dimensional array.
arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [3]:
arr.sum()

6.969633205349975

**Or:**

In [4]:
def sum_array(arr):
    x = 0
    for i in range(len(arr)):
        for j in arr[i]:
            x += j
    return f"The sum of the inputted array is {x}"
sum_array(arr)

'The sum of the inputted array is 6.969633205349975'

## 2.	Write a Python Program to find largest element in an array?

In [5]:
arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [6]:
arr.max() #largest element

2.240893199201458

**Or:**

In [7]:
def greatest_ele(arr):
    max = 0
    for i in range(len(arr)):
        for j in arr[i]:
            if max < j:
                max = j

    return f"The greatest element of this array is {max}"
greatest_ele(arr)

'The greatest element of this array is 2.240893199201458'

## 3.	Write a Python Program for array rotation?

In [8]:
arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [9]:
#Rotation i.e. Transpose
arr.T

array([[ 1.76405235,  2.2408932 ,  0.95008842],
       [ 0.40015721,  1.86755799, -0.15135721],
       [ 0.97873798, -0.97727788, -0.10321885]])

## 4.	Write a Python Program to Split the array and add the first part to the end?

In [10]:
def split_add(arr):
    
    a = arr[1:]
    a = pd.DataFrame(a) # Converting 'a' to DataFrame so that an additional row can be appended.
    a.loc[len(a)+1] = arr[0]
    a = np.array(a) # converting the 'a' back to array.
    return a
    
split_add(arr)

array([[ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 1.76405235,  0.40015721,  0.97873798]])

## 5.	Write a Python Program to check if given array is Monotonic?

**Monotonicity means either the array is in increasing order or in decreasing order.**

In [11]:
arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [37]:
def if_mono(arr):
    
    a = [] # a list containing all the elements of arr.
    
    i = 0
    j = 0
    while i < len(arr): #if our array is not 1-dimensional.
        while j < len(arr):
            a.append(arr[i][j])
            j +=1
        i+=1
    
    if all(a[i]>=a[i+1] for i in range(0,len(a)-1) or a[i]<=a[i+1] for i in range(0,len(a)-1)):
            return "The given array is montonic!"
    else:
        return "The given array ain't montonic!"
    
if_mono(arr)

'The given array is montonic!'